"""
NFL team and player mappings
"""

# NFL team mappings
NFL_TEAMS = {
    "Cardinals": "Arizona Cardinals",
    "Falcons": "Atlanta Falcons",
    "Ravens": "Baltimore Ravens",
    "Bills": "Buffalo Bills",
    "Panthers": "Carolina Panthers",
    "Bears": "Chicago Bears",
    "Bengals": "Cincinnati Bengals",
    "Browns": "Cleveland Browns",
    "Cowboys": "Dallas Cowboys",
    "Broncos": "Denver Broncos",
    "Lions": "Detroit Lions",
    "Packers": "Green Bay Packers",
    "Texans": "Houston Texans",
    "Colts": "Indianapolis Colts",
    "Jaguars": "Jacksonville Jaguars",
    "Chiefs": "Kansas City Chiefs",
    "Raiders": "Las Vegas Raiders",
    "Chargers": "Los Angeles Chargers",
    "Rams": "Los Angeles Rams",
    "Dolphins": "Miami Dolphins",
    "Vikings": "Minnesota Vikings",
    "Patriots": "New England Patriots",
    "Saints": "New Orleans Saints",
    "Giants": "New York Giants",
    "Jets": "New York Jets",
    "Eagles": "Philadelphia Eagles",
    "Steelers": "Pittsburgh Steelers",
    "49ers": "San Francisco 49ers",
    "Seahawks": "Seattle Seahawks",
    "Buccaneers": "Tampa Bay Buccaneers",
    "Titans": "Tennessee Titans",
    "Commanders": "Washington Commanders"
}

# Player to team mapping for 2025 season (updated rosters)
PLAYER_TEAMS_2025 = {
    # QBs
    "Saquon Barkley": "Philadelphia Eagles",
    "A.J. Brown": "Philadelphia Eagles",
    "DeVonta Smith": "Philadelphia Eagles",
    "Devonta Smith": "Philadelphia Eagles",  # Alternative spelling
    "George Pickens": "Dallas Cowboys",
    "CeeDee Lamb": "Dallas Cowboys",
    "Jake Ferguson": "Dallas Cowboys",
    "Dallas Goedert": "Philadelphia Eagles",
    "Javonte Williams": "Denver Broncos",
    "Terry McLaurin": "Washington Commanders",
    "Malik Nabers": "New York Giants",
    "Jayden Daniels": "Washington Commanders",
    "Russel Wilson": "New York Giants",
    "Russell Wilson": "New York Giants",
    "Lamar Jackson": "Baltimore Ravens",
    "Josh Allen": "Buffalo Bills",
    "Zay Flowers": "Baltimore Ravens",
    "Khalil Shakir": "Buffalo Bills",
    "James Cook": "Buffalo Bills",
    "Dalton Kincaid": "Buffalo Bills",
    "Derrick Henry": "Baltimore Ravens",
    "Mark Andrews": "Baltimore Ravens",
    "Aaron Jones": "Minnesota Vikings",
    "D'Andre Swift": "Chicago Bears",
    "T.J. Hockenson": "Minnesota Vikings",
    "Justin Jefferson": "Minnesota Vikings",
    "J.J. McCarthy": "Minnesota Vikings",
    "Caleb Williams": "Chicago Bears",
    "D.J. Moore": "Chicago Bears",
    "Tucker Kraft": "Green Bay Packers",
    "Kyren Williams": "Los Angeles Rams",
    "Geno Smith": "Seattle Seahawks",
    "Justin Herbert": "Los Angeles Chargers",
    "Jakobi Meyers": "Las Vegas Raiders",
    "Keenan Allen": "Chicago Bears",
    "Patrick Mahomes": "Kansas City Chiefs",
    "Bucky Irving": "Tampa Bay Buccaneers",
    "Bijan Robinson": "Atlanta Falcons",
    "Jordan Mason": "San Francisco 49ers",
    "Kenneth Walker III": "Seattle Seahawks",
    "Amon-Ra St. Brown": "Detroit Lions",
    "Jared Goff": "Detroit Lions",
    "Sam LaPorta": "Detroit Lions",
    "Kyler Murray": "Arizona Cardinals",
    "Sam Darnold": "Seattle Seahawks",
    "Trey Benson": "Arizona Cardinals",
    "Jaxon Smith-Njigba": "Seattle Seahawks",
    "Marvin Harrison Jr.": "Arizona Cardinals",
    "Trey McBride": "Arizona Cardinals",
    "Michael Wilson": "Arizona Cardinals",
    "Zach Charbonnet": "Seattle Seahawks",
    "Matthew Stafford": "Los Angeles Rams",
    "Daniel Jones": "Indianapolis Colts",
    "Puka Nacua": "Los Angeles Rams",
    "Jonathan Taylor": "Indianapolis Colts",
    "Davante Adams": "Los Angeles Chargers",
    "Michael Pittman Jr.": "Indianapolis Colts",
    "Omarion Hampton": "Los Angeles Chargers",
    "Spencer Rattler": "New Orleans Saints",
    "David Montgomery": "Detroit Lions",
    "Jordan Love": "Green Bay Packers",
    "Mac Jones": "San Francisco 49ers",
    "Christian McCaffrey": "San Francisco 49ers",
    "Bo Nix": "Denver Broncos",
    "Jalen Hurts": "Philadelphia Eagles",
    "Stefon Diggs": "Houston Texans",
    "Drake Maye": "New England Patriots",
    "Dyami Brown": "Washington Commanders",
    "Isiah Pacheco": "Kansas City Chiefs",
    "Trevor Lawrence": "Jacksonville Jaguars",
    "Xavier Worthy": "Kansas City Chiefs",
    "Travis Kelce": "Kansas City Chiefs",
    "Marquise Brown": "Kansas City Chiefs",
    "Travis Hunter": "Colorado Buffaloes",  # College player
    "Travis Etienne": "Jacksonville Jaguars",
    "Jahmyr Gibbs": "Detroit Lions",
    "Tyler Allgeier": "Atlanta Falcons",
    "Drake London": "Atlanta Falcons",
    "Allen": "Josh Allen",  # Shorthand
    "Kincaid": "Dalton Kincaid",
    "Roschon Johnson": "Chicago Bears",
    "Zach Ertz": "Washington Commanders",
    "Aaron Rodgers": "New York Jets",
    "Joe Flacco": "Indianapolis Colts",
    "Ja'Marr Chase": "Cincinnati Bengals",
    "DK Metcalf": "Seattle Seahawks",
    "Jaylen Warren": "Pittsburgh Steelers",
    "Rome Odunze": "Chicago Bears",
    "Michael Penix Jr.": "Atlanta Falcons",
    "Cade Otton": "Tampa Bay Buccaneers",
    "Baker Mayfield": "Tampa Bay Buccaneers",
}

# Legacy alias for backwards compatibility
PLAYER_TEAMS_2024 = PLAYER_TEAMS_2025
