"""Initial local setup

Revision ID: 0f30369770ee
Revises: 
Create Date: 2025-11-24 20:17:09.099018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f30369770ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('position_group', sa.String(length=20), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('current_team', sa.String(length=50), nullable=True),
    sa.Column('team_abbreviation', sa.String(length=10), nullable=True),
    sa.Column('previous_teams', sa.Text(), nullable=True),
    sa.Column('espn_player_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('team_name_short', sa.String(length=50), nullable=True),
    sa.Column('team_abbr', sa.String(length=10), nullable=False),
    sa.Column('espn_team_id', sa.String(length=50), nullable=True),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('league', sa.String(length=50), nullable=True),
    sa.Column('conference', sa.String(length=50), nullable=True),
    sa.Column('division', sa.String(length=50), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('win_percentage', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('division_rank', sa.Integer(), nullable=True),
    sa.Column('conference_rank', sa.Integer(), nullable=True),
    sa.Column('league_rank', sa.Integer(), nullable=True),
    sa.Column('playoff_seed', sa.Integer(), nullable=True),
    sa.Column('games_behind', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('streak', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('alternate_color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('season_year', sa.String(length=10), nullable=True),
    sa.Column('last_game_date', sa.Date(), nullable=True),
    sa.Column('next_game_date', sa.Date(), nullable=True),
    sa.Column('api_data_url', sa.Text(), nullable=True),
    sa.Column('last_stats_update', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_team_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('betting_site_id', sa.String(length=100), nullable=True),
    sa.Column('bet_type', sa.String(length=50), nullable=True),
    sa.Column('betting_site', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('api_fetched', sa.String(length=3), nullable=True),
    sa.Column('bet_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('bet_date', sa.String(length=20), nullable=True),
    sa.Column('wager', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('original_odds', sa.Integer(), nullable=True),
    sa.Column('boosted_odds', sa.Integer(), nullable=True),
    sa.Column('final_odds', sa.Integer(), nullable=True),
    sa.Column('is_boosted', sa.Boolean(), nullable=True),
    sa.Column('potential_winnings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_winnings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('has_insurance', sa.Boolean(), nullable=True),
    sa.Column('insurance_type', sa.String(length=50), nullable=True),
    sa.Column('insurance_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('insurance_triggered', sa.Boolean(), nullable=True),
    sa.Column('total_legs', sa.Integer(), nullable=True),
    sa.Column('legs_won', sa.Integer(), nullable=True),
    sa.Column('legs_lost', sa.Integer(), nullable=True),
    sa.Column('legs_pending', sa.Integer(), nullable=True),
    sa.Column('legs_live', sa.Integer(), nullable=True),
    sa.Column('legs_void', sa.Integer(), nullable=True),
    sa.Column('last_api_update', sa.DateTime(), nullable=True),
    sa.Column('secondary_bettors', sa.JSON(), nullable=True),
    sa.Column('watchers', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('player_team', sa.String(length=50), nullable=True),
    sa.Column('player_position', sa.String(length=10), nullable=True),
    sa.Column('home_team', sa.String(length=50), nullable=False),
    sa.Column('away_team', sa.String(length=50), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=True),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.Column('game_time', sa.Time(), nullable=True),
    sa.Column('game_status', sa.String(length=20), nullable=True),
    sa.Column('sport', sa.String(length=50), nullable=True),
    sa.Column('parlay_sport', sa.String(length=50), nullable=True),
    sa.Column('bet_type', sa.String(length=50), nullable=False),
    sa.Column('stat_type', sa.String(length=50), nullable=True),
    sa.Column('bet_line_type', sa.String(length=20), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('achieved_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('player_season_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('player_last_5_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vs_opponent_avg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_vs_season', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('original_leg_odds', sa.Integer(), nullable=True),
    sa.Column('boosted_leg_odds', sa.Integer(), nullable=True),
    sa.Column('final_leg_odds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_hit', sa.Boolean(), nullable=True),
    sa.Column('void_reason', sa.String(length=100), nullable=True),
    sa.Column('current_quarter', sa.String(length=10), nullable=True),
    sa.Column('time_remaining', sa.String(length=20), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('is_home_game', sa.Boolean(), nullable=True),
    sa.Column('weather_conditions', sa.String(length=100), nullable=True),
    sa.Column('injury_during_game', sa.Boolean(), nullable=True),
    sa.Column('dnp_reason', sa.String(length=100), nullable=True),
    sa.Column('leg_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet_legs')
    op.drop_table('bets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('players')
    # ### end Alembic commands ###
